#!/bin/bash

head /etc/passwd \[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[[C[C[C[C[C[C[C[C[C[C[C[A
[Ahead /etc/passwd [1;3j[1;3r[D[D[D[A[A[A[A[B[B
[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B[B